version: "3.8"
services:
  app:
    build: .
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gymdb
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run start
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: