openapi: 3.0.3
info:
  title: Super Admin Badges API
  version: 1.0.0
  description: >
    API pour la gestion des badges par un super administrateur.
servers:
  - url: http://localhost:3000/badges

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Badge:
      type: object
      properties:
        name:
          type: string
          example: Marathon Finisher
        description:
          type: string
          example: Awarded for completing a marathon
        rules:
          type: string
          example: Run 42km in one session

security:
  - bearerAuth: []

paths:
  /:
    post:
      summary: Créer un badge
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Badge'
      responses:
        201:
          description: Badge créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Badge'

    get:
      summary: Lister tous les badges
      security:
        - bearerAuth: []
      responses:
        200:
          description: Liste des badges
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Badge'

  /{id}:
    put:
      summary: Modifier un badge existant
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Badge'
      responses:
        200:
          description: Badge mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Badge'

    delete:
      summary: Supprimer un badge
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Badge supprimé
