openapi: 3.0.3
info:
  title: Super Admin Exercise Types API
  version: 1.0.0
  description: >
    API pour la gestion des types d'exercices par un super administrateur.
servers:
  - url: http://localhost:3000/exercise-types

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ExerciseType:
      type: object
      properties:
        name:
          type: string
          example: Cardio
        description:
          type: string
          example: Exercises to improve heart and lung endurance
        musclesTargeted:
          type: array
          items:
            type: string
          example: ["Legs", "Heart"]

security:
  - bearerAuth: []

paths:
  /:
    post:
      summary: Créer un type d'exercice
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseType'
      responses:
        201:
          description: Type d'exercice créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseType'

    get:
      summary: Lister tous les types d'exercices
      security:
        - bearerAuth: []
      responses:
        200:
          description: Liste des types d'exercices
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExerciseType'

  /{id}:
    put:
      summary: Modifier un type d'exercice existant
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExerciseType'
      responses:
        200:
          description: Type d'exercice mis à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExerciseType'

    delete:
      summary: Supprimer un type d'exercice
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Type d'exercice supprimé
