openapi: 3.0.3
info:
  title: Super Admin Users API
  version: 1.0.0
  description: >
    API pour la gestion des utilisateurs par un super administrateur.
servers:
  - url: http://localhost:3000/users

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
          example: admin
        role:
          type: string
          enum: [SUPER_ADMIN, ADMIN, USER]
        active:
          type: boolean
          example: true

security:
  - bearerAuth: []

paths:
  /:
    get:
      summary: Lister tous les utilisateurs
      security:
        - bearerAuth: []
      responses:
        200:
          description: Liste des utilisateurs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'

  /{id}/deactivate:
    patch:
      summary: Désactiver un utilisateur
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Utilisateur désactivé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /{id}/activate:
    patch:
      summary: Réactiver un utilisateur
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Utilisateur activé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /{id}:
    delete:
      summary: Supprimer un utilisateur
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Utilisateur supprimé
