openapi: 3.0.3
info:
  title: Client User API
  version: 1.0.0
  description: >
    API pour les utilisateurs finaux (`USER`) : création et exploration de défis, suivi d’entraînements, badges et classement.
servers:
  - url: http://localhost:3000/user

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Challenge:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        difficulty:
          type: string
        type:
          type: string
        duration:
          type: integer
        createdBy:
          type: string
    Workout:
      type: object
      properties:
        challenge:
          type: string
        date:
          type: string
          format: date-time
        durationMinutes:
          type: integer
        caloriesBurned:
          type: number
        completed:
          type: boolean
    Badge:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        rules:
          type: string

security:
  - bearerAuth: []

paths:
  /challenges:
    post:
      summary: Créer un défi
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Challenge'
      responses:
        201:
          description: Défi créé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Challenge'

    get:
      summary: Explorer les défis
      security:
        - bearerAuth: []
      parameters:
        - name: difficulty
          in: query
          schema:
            type: string
        - name: type
          in: query
          schema:
            type: string
        - name: duration
          in: query
          schema:
            type: integer
      responses:
        200:
          description: Liste des défis
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Challenge'

  /workouts:
    post:
      summary: Enregistrer un entraînement
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Workout'
      responses:
        201:
          description: Entraînement enregistré
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'

    get:
      summary: Voir ses entraînements
      security:
        - bearerAuth: []
      responses:
        200:
          description: Liste des entraînements de l'utilisateur
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'

  /leaderboard:
    get:
      summary: Voir le classement des utilisateurs
      security:
        - bearerAuth: []
      responses:
        200:
          description: Classement
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    completedCount:
                      type: integer

  /badges:
    get:
      summary: Voir ses badges
      security:
        - bearerAuth: []
      responses:
        200:
          description: Liste des badges de l'utilisateur
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Badge'
