name: CI/CD - Build, Test & Deploy

on:
  push:
    branches:
      - master

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build & start containers (CI)
        run: |
          docker-compose down || true
          docker-compose up -d --build

      - name: Show containers
        run: docker ps -a

      - name: Backend logs
        run: docker-compose logs app

      - name: Deploy to VPS
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Créer le dossier si absent
            if [ ! -d /opt/Gym-Api ]; then
              mkdir -p /opt/Gym-Api
              cd /opt/Gym-Api
              git clone https://github.com/djellalifouaddev/Gym-Api.git .
            else
              cd /opt/Gym-Api
              git pull
            fi
            docker-compose down || true
            docker-compose build --no-cache
            docker-compose up -d
